//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Debug, EnumIter, DeriveActiveEnum, Eq, PartialEq, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum Repeat {
    #[sea_orm(string_value = "once")]
    ONCE,
    #[sea_orm(string_value = "daily")]
    DAILY,
    #[sea_orm(string_value = "weekly")]
    WEEKLY,
    #[sea_orm(string_value = "monthly")]
    MONTHLY,
    #[sea_orm(string_value = "yearly")]
    YEARLY,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "schedule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub date: DateTimeUtc,
    pub remind: Option<bool>,
    #[sea_orm(column_type = "Text")]
    pub repeat: Repeat,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
